controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

book_details:
    path: /book/{id}
    controller: App\Controller\HomeController::bookDetails
